### ISSUE TITLE
Help Wanted: writer to cover subprojects/dependencies

### ISSUE THREAD

**Issue by jberkus** [kubernetes-sigs/lwkd#205]
# WANTED: Subprojects Writer

## Responsibilities

Kubernetes has broken up its monorepo, and as such many essential parts of Kubernetes exist as subprojects or external projects.  These would include things like (but by no means limited to):

- CSI and CNI
- kind
- kubebuilder
- Cloud Providers
- CSI drivers
- Etcd
- Kustomize
- Prometheus
- Prow
- Ingress-NGINX

... and many others.  To help the community stay on top of developments across our whole network of dependencies and components, we'd like someone who can scan some or all of them for major updates and changes, and write up very brief notices (10-30 words) of them for LWKD.

Examples:

* AWS-Cloud-Provider supports [IPv6 Fargate Nodes](https://github.com/kubernetes/cloud-provider-aws/pull/565)
* Kubespray: handle [SSL Certs better](https://github.com/kubernetes-sigs/kubespray/pull/10215) for air-gapped deployments

Time permitting, you might also write short 1-2 paragraph (60-200 words) reviews of these subprojects and dependencies and how they fit into the Kubernetes ecosystem.

You would also occasionally be responsible for publishing the main LWKD issue during weeks when the other contributors are unavailable.

## Requirements

Candidates must have some experience with Kubernetes and its code ecosystem, and already be somewhat familiar with how the various components fit together, in theory if not in practice.   They must also have adequate composition skills in English. The ideal writer will be able to look for subprojects to write about without explicit direction or oversight.

**Comment by sftim** [comment]
(nit)
/retitle Help Wanted: writer to cover subprojects/dependencies

**Comment by mfahlandt** [comment]
As i built the script, i would also volunteer to cover this section in the future for writing the summaries if the help is still wanted / need :)
