### ISSUE TITLE
Email subscription seems to be not working

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/lwkd#215]
Hello,

I tried to subscribe to this amazing service on gmail.  But I never received an email.

**Comment by jberkus** [comment]
Can you try again?  We had some issues with Buttondown that are now resolved.

If it still fails, can you give us a 1,2,3 of what you tried and what happened?

**Comment by kannon92** [comment]
I tried again.  

I go to subscribe via email and put in my gmail and then I wait for an email.  It doesn't seem to come.  I tried both my work email and personal email and it didn't come to either.

**Comment by kannon92** [comment]
Alright.  It looks like it went through.
