### ISSUE TITLE
Create a tool to list all release updates from related projects

### ISSUE THREAD

**Issue by jberkus** [kubernetes-sigs/lwkd#266]
As part of having updates from "related projects" (see #232) it would be very useful to have a tool which was capable of collecting a list of release announcements from the last week+ for a configured list of repos.  This would give us a list of announcements to scan and see if any of them are newsworthy.  Eventually, if the output of such a tool were web-formatted, it would also be a useful page for Kubernetes Devs and cluster owners.

**Comment by AvineshTripathi** [comment]
Hey @jberkus will this tool  be spefcific to releases only or can be major PRs and Issues created with certain labels(that we feel would be a ctritical/important)?

**Comment by jberkus** [comment]
Mario has done some work on this: https://github.com/mfahlandt/news-crawler
