### ISSUE TITLE
We should have a style guide for LWKD

### ISSUE THREAD

**Issue by jberkus** [kubernetes-sigs/lwkd#267]
It would help contributors to LWKD to have a style guide.

While we can borrow some things (mainly about project/tool naming) from the [Docs style guide](https://kubernetes.io/docs/contribute/style/style-guide/), we need some guide materials that are peculiar to LWKD.

**Comment by colossus06** [comment]
hii, can you explain what do you have in mind regarding the style?

**Comment by jberkus** [comment]
This is the Kubernetes docs style guide:

https://kubernetes.io/docs/contribute/style/style-guide/

An LWKD style guide would include the elements that are relevant to us from that style guide, plus the other aspects of "LWKD" style, such as brevity, how we do merge entries, how links are handled, etc.
