### ISSUE TITLE
Release Notes - relevent Projects 12-05-2023 - 12-12-2023

### ISSUE THREAD

**Issue by mfahlandt** [kubernetes-sigs/lwkd#270]
**Your Item for LWKD**
Release Notes of Relevant Projects listed in #265 for the Week of 12-05-2023 - 12-12-2023

# Latest Releases for 2023-12-05 
#### 2023-12-07 Please check out [CHANGELOG](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md) for a full list of changes. And make sure to read [upgrade guide](https://github.com/etcd-io/website/blob/main/content/en/docs/v3.5/upgrades/upgrade_3_5.md) before upgrading etcd (there may be breaking changes).

For installation guides, please check out [play.etcd.io](http://play.etcd.io) and [operating etcd](https://github.com/etcd-io/etcd/tree/master/Documentation#operating-etcd-clusters). Latest support status for common architectures and operating systems can be found at [supported platforms](https://github.com/etcd-io/website/blob/main/content/en/docs/v3.5/op-guide/supported-platform.md).

###### Linux

```bash
ETCD_VER=v3.5.11

# choose either URL
GOOGLE_URL=https://storage.googleapis.com/etcd
GITHUB_URL=https://github.com/etcd-io/etcd/releases/download
DOWNLOAD_URL=${GOOGLE_URL}

rm -f /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
rm -rf /tmp/etcd-download-test && mkdir -p /tmp/etcd-download-test

curl -L ${DOWNLOAD_URL}/${ETCD_VER}/etcd-${ETCD_VER}-linux-amd64.tar.gz -o /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
tar xzvf /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz -C /tmp/etcd-download-test --strip-components=1
rm -f /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz

/tmp/etcd-download-test/etcd --version
/tmp/etcd-download-test/etcdctl version
/tmp/etcd-download-test/etcdutl version
```

```bash
# start a local etcd server
/tmp/etcd-download-test/etcd

# write,read to etcd
/tmp/etcd-download-test/etcdctl --endpoints=localhost:2379 put foo bar
/tmp/etcd-download-test/etcdctl --endpoints=localhost:2379 get foo
```

###### macOS (Darwin)

```bash
ETCD_VER=v3.5.11

# choose either URL
GOOGLE_URL=https://storage.googleapis.com/etcd
GITHUB_URL=https://github.com/etcd-io/etcd/releases/download
DOWNLOAD_URL=${GOOGLE_URL}

rm -f /tmp/etcd-${ETCD_VER}-darwin-amd64.zip
rm -rf /tmp/etcd-download-test && mkdir -p /tmp/etcd-download-test

curl -L ${DOWNLOAD_URL}/${ETCD_VER}/etcd-${ETCD_VER}-darwin-amd64.zip -o /tmp/etcd-${ETCD_VER}-darwin-amd64.zip
unzip /tmp/etcd-${ETCD_VER}-darwin-amd64.zip -d /tmp && rm -f /tmp/etcd-${ETCD_VER}-darwin-amd64.zip
mv /tmp/etcd-${ETCD_VER}-darwin-amd64/* /tmp/etcd-download-test && rm -rf mv /tmp/etcd-${ETCD_VER}-darwin-amd64

/tmp/etcd-download-test/etcd --version
/tmp/etcd-download-test/etcdctl version
/tmp/etcd-download-test/etcdutl version
```

###### Docker

etcd uses [`gcr.io/etcd-development/etcd`](https://gcr.io/etcd-development/etcd) as a primary container registry, and [`quay.io/coreos/etcd`](https://quay.io/coreos/etcd) as secondary.

```bash
rm -rf /tmp/etcd-data.tmp && mkdir -p /tmp/etcd-data.tmp && \
  docker rmi gcr.io/etcd-development/etcd:v3.5.11 || true && \
  docker run \
  -p 2379:2379 \
  -p 2380:2380 \
  --mount type=bind,source=/tmp/etcd-data.tmp,destination=/etcd-data \
  --name etcd-gcr-v3.5.11 \
  gcr.io/etcd-development/etcd:v3.5.11 \
  /usr/local/bin/etcd \
  --name s1 \
  --data-dir /etcd-data \
  --listen-client-urls http://0.0.0.0:2379 \
  --advertise-client-urls http://0.0.0.0:2379 \
  --listen-peer-urls http://0.0.0.0:2380 \
  --initial-advertise-peer-urls http://0.0.0.0:2380 \
  --initial-cluster s1=http://0.0.0.0:2380 \
  --initial-cluster-token tkn \
  --initial-cluster-state new \
  --log-level info \
  --logger zap \
  --log-outputs stderr

docker exec etcd-gcr-v3.5.11 /usr/local/bin/etcd --version
docker exec etcd-gcr-v3.5.11 /usr/local/bin/etcdctl version
docker exec etcd-gcr-v3.5.11 /usr/local/bin/etcdutl version
docker exec etcd-gcr-v3.5.11 /usr/local/bin/etcdctl endpoint health
docker exec etcd-gcr-v3.5.11 /usr/local/bin/etcdctl put foo bar
docker exec etcd-gcr-v3.5.11 /usr/local/bin/etcdctl get foo
```
#### 2023-12-08Welcome to the v1.7.11 release of containerd!

The eleventh patch release for containerd 1.7 contains various fixes and updates including
one security issue.

### Notable Updates

* **Fix Windows default path overwrite issue** ([#9440](https://github.com/containerd/containerd/pull/9440))
* **Update push to always inherit distribution sources from parent** ([#9452](https://github.com/containerd/containerd/pull/9452))
* **Update shim to use net dial for gRPC shim sockets** ([#9458](https://github.com/containerd/containerd/pull/9458))
* **Fix otel version incompatibility** ([#9483](https://github.com/containerd/containerd/pull/9483))
* **Fix Windows snapshotter blocking snapshot GC on remove failure** ([#9482](https://github.com/containerd/containerd/pull/9482))
* **Mask `/sys/devices/virtual/powercap` path in runtime spec and deny in default apparmor profile** ([GHSA-7ww5-4wqc-m92c](https://github.com/containerd/containerd/security/advisories/GHSA-7ww5-4wqc-m92c))

### Deprecation Warnings

* **Emit deprecation warning for AUFS snapshotter** ([#9436](https://github.com/containerd/containerd/pull/9436))
* **Emit deprecation warning for v1 runtime** ([#9450](https://github.com/containerd/containerd/pull/9450))
* **Emit deprecation warning for deprecated CRI configs** ([#9469](https://github.com/containerd/containerd/pull/9469))
* **Emit deprecation warning for CRI v1alpha1 usage** ([#9479](https://github.com/containerd/containerd/pull/9479))
* **Emit deprecation warning for CRIU config in CRI** ([#9481](https://github.com/containerd/containerd/pull/9481))

See the changelog for complete list of changes

Please try out the release binaries and report any issues at
https://github.com/containerd/containerd/issues.

### Contributors

* Samuel Karp
* Derek McGowan
* Phil Estes
* Bjorn Neergaard
* Danny Canter
* Sebastiaan van Stijn
* ruiwen-zhao
* Akihiro Suda
* Amit Barve
* Charity Kathure
* Maksym Pavlenko
* Milas Bowman
* Paweł Gronowski
* Wei Fu

### Changes
<details><summary>39 commits</summary>
<p>

* [release/1.7] Prepare release notes for v1.7.11 ([#9491](https://github.com/containerd/containerd/pull/9491))
  * [`dfae68bc3`](https://github.com/containerd/containerd/commit/dfae68bc3e614a091d0a468c9026da370e3de0d9) Prepare release notes for v1.7.11
* [release/1.7] update to go1.20.12, test go1.21.5 ([#9352](https://github.com/containerd/containerd/pull/9352))
  * [`0d314401d`](https://github.com/containerd/containerd/commit/0d314401d9b9ad470153dc3d09f6d9cd7d527697) update to go1.20.12, test go1.21.5
  * [`1ec1ae2c6`](https://github.com/containerd/containerd/commit/1ec1ae2c6b6458b5d000af1ec6263b4ee337cd58) update to go1.20.11, test go1.21.4
* Github Security Advisory [GHSA-7ww5-4wqc-m92c](https://github.com/containerd/containerd/security/advisories/GHSA-7ww5-4wqc-m92c)
  * [`cb804da21`](https://github.com/containerd/containerd/commit/cb804da2101074c769a2a327597c9595b38bb4f0) contrib/apparmor: deny /sys/devices/virtual/powercap
  * [`40162a576`](https://github.com/containerd/containerd/commit/40162a576232b7d95325f85334590ea295d2ed2e) oci/spec: deny /sys/devices/virtual/powercap
* [release/1.7] Don't block snapshot garbage collection on Remove failures ([#9482](https://github.com/containerd/containerd/pull/9482))
  * [`ed7c6895b`](https://github.com/containerd/containerd/commit/ed7c6895bd3b33ccc7cfbc8cbd43f6a31333328a) Don't block snapshot garbage collection on Remove failures
* [release/1.7] Add warning for CRIU config usage ([#9481](https://github.com/containerd/containerd/pull/9481))
  * [`1fdefdd22`](https://github.com/containerd/containerd/commit/1fdefdd2242fcf704a11f1d6b5149e056ce98ed3) Add warning for CRIU config usage
* [release/1.7] Fix otel version incompatibility ([#9483](https://github.com/containerd/containerd/pull/9483))
  * [`f8f659e66`](https://github.com/containerd/containerd/commit/f8f659e66c6ec56fef092dced085d129c0e67176) Add HTTP client update function to tracing library
  * [`807ddd658`](https://github.com/containerd/containerd/commit/807ddd658b4cd6c0325204e7a19a4561a10906d2) fix(tracing): use latest version of semconv
* [release/1.7] Add cri-api v1alpha2 usage warning to all api calls ([#9479](https://github.com/containerd/containerd/pull/9479))
  * [`dc45bc838`](https://github.com/containerd/containerd/commit/dc45bc8381fa2cd903e871c81ce7b4c08e82ca3b) Add cri-api v1alpha2 usage warning to all api calls
* [release/1.7] cri: add deprecation warnings for deprecated CRI configs ([#9469](https://github.com/containerd/containerd/pull/9469))
  * [`9d1bad62e`](https://github.com/containerd/containerd/commit/9d1bad62e16f31e0b06c75e1007a623879529a6d) deprecation: fix missing spaces in warnings
  * [`51a604c07`](https://github.com/containerd/containerd/commit/51a604c0733437f4b7a20aa5ec1e6d4b4f0ab96e) cri: add deprecation warning for runtime_root
  * [`8040e74bf`](https://github.com/containerd/containerd/commit/8040e74bf8e6c25c02bb461b82f482cff24ce611) cri: add deprecation warning for rutnime_engine
  * [`99adc40eb`](https://github.com/containerd/containerd/commit/99adc40eb28db7cb93c378ff8bceb8e77559ae09) cri: add deprecation warning for default_runtime
  * [`afef7ec64`](https://github.com/containerd/containerd/commit/afef7ec646910ce1db3e824bfe17848428f3b47b) cri: add warning for untrusted_workload_runtime
  * [`6220dc190`](https://github.com/containerd/containerd/commit/6220dc1909883119a960bc96c496ae2361b94749) cri: add warning for old form of systemd_cgroup
* [release/1.7] runtime/v2: net.Dial gRPC shim sockets before trying grpc ([#9458](https://github.com/containerd/containerd/pull/9458))
  * [`80f96cd18`](https://github.com/containerd/containerd/commit/80f96cd188949bd9fa16256a8ff0b858ef692f20) runtime/v2: net.Dial gRPC shim sockets before trying grpc
* [release/1.7] tasks: emit warning for v1 runtime and runc v1 runtime ([#9450](https://github.com/containerd/containerd/pull/9450))
  * [`f471bb2b8`](https://github.com/containerd/containerd/commit/f471bb2b8e5a902ad8901c7c0db85ecead8c1730) tasks: emit warning for runc v1 runtime
  * [`329e1d487`](https://github.com/containerd/containerd/commit/329e1d487e7cc5c2773a2472df56b6eb75ae9194) tasks: emit warning for v1 runtime
* [release/1.7] push: always inherit distribution sources from parent ([#9452](https://github.com/containerd/containerd/pull/9452))
  * [`4464fde12`](https://github.com/containerd/containerd/commit/4464fde12985d98a9edbf124c54afa1156415572) push: always inherit distribution sources from parent
* [release/1.7] Update tar tests to run on Darwin ([#9451](https://github.com/containerd/containerd/pull/9451))
  * [`7e069ee25`](https://github.com/containerd/containerd/commit/7e069ee25868e5c8a67610720f8280c3451a3103) Update tar tests to run on Darwin
* [release/1.7] ctr: Add sandbox flag to ctr run ([#9449](https://github.com/containerd/containerd/pull/9449))
  * [`5fc0e4e61`](https://github.com/containerd/containerd/commit/5fc0e4e6151dafa4d5ca8837f3d99b6a8e816866) ctr: Add sandbox flag to ctr run
* [release/1.7] Windows default path overwrite fix ([#9440](https://github.com/containerd/containerd/pull/9440))
  * [`31fe03764`](https://github.com/containerd/containerd/commit/31fe03764c436677a1db9be24c25f7c11780eceb) Fix windows default path overwrite issue
* [release/1.7] snapshots: emit deprecation warning for aufs ([#9436](https://github.com/containerd/containerd/pull/9436))
  * [`625b35e4b`](https://github.com/containerd/containerd/commit/625b35e4bb26ee021713f2692143bf37f9a98bdd) snapshots: emit deprecation warning for aufs
</p>
</details>

### Dependency Changes

* **github.com/felixge/httpsnoop**                                   v1.0.3 **_new_**
* **go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp**  v0.45.0 **_new_**

Previous release can be found at [v1.7.10](https://github.com/containerd/containerd/releases/tag/v1.7.10)
### Release notes for containerd 1.6.26#### 2023-12-08Welcome to the v1.6.26 release of containerd!

The twenty-sixth patch release for containerd 1.6 contains various fixes and updates.

### Notable Updates

* **Fix windows default path overwrite issue** ([#9441](https://github.com/containerd/containerd/pull/9441))
* **Update push to inherit distribution sources from parent** ([#9453](https://github.com/containerd/containerd/pull/9453))
* **Mask `/sys/devices/virtual/powercap` path in runtime spec and deny in default apparmor profile** ([GHSA-7ww5-4wqc-m92c](https://github.com/containerd/containerd/security/advisories/GHSA-7ww5-4wqc-m92c))

### Deprecation Warnings

* **Emit deprecation warning for AUFS snapshotter usage** ([#9448](https://github.com/containerd/containerd/pull/9448))
* **Emit deprecation warning for v1 runtime usage** ([#9468](https://github.com/containerd/containerd/pull/9468))
* **Emit deprecation warning for CRI v1alpha1 usage** ([#9468](https://github.com/containerd/containerd/pull/9468))

See the changelog for complete list of changes

Please try out the release binaries and report any issues at
https://github.com/containerd/containerd/issues.

### Contributors

* Samuel Karp
* Derek McGowan
* Kohei Tokunaga
* Phil Estes
* Bjorn Neergaard
* Sebastiaan van Stijn
* Brian Goff
* Charity Kathure
* Kazuyoshi Kato
* Milas Bowman
* Wei Fu
* ruiwen-zhao

### Changes
<details><summary>30 commits</summary>
<p>

* [release/1.6] Prepare release notes for v1.6.26 ([#9490](https://github.com/containerd/containerd/pull/9490))
  * [`ac5c5d3e0`](https://github.com/containerd/containerd/commit/ac5c5d3e03ab3c5b8103a1c0bd9931389f7a8fcf) Prepare release notes for v1.6.26
* Github Security Advisory [GHSA-7ww5-4wqc-m92c](https://github.com/containerd/containerd/security/advisories/GHSA-7ww5-4wqc-m92c)
  * [`02f07fe19`](https://github.com/containerd/containerd/commit/02f07fe1994a3ddda3626c1ede2e32bc82b8e426) contrib/apparmor: deny /sys/devices/virtual/powercap
  * [`c94577e78`](https://github.com/containerd/containerd/commit/c94577e78d2924ddeb90d1601e31b50ee3acac48) oci/spec: deny /sys/devices/virtual/powercap
* [release/1.6] update to go1.20.12, test go1.21.5 ([#9472](https://github.com/containerd/containerd/pull/9472))
  * [`7cbdfc92e`](https://github.com/containerd/containerd/commit/7cbdfc92ef38f789f1a2773fa6fac405d361a6cc) update to go1.20.12, test go1.21.5
  * [`024b1cce6`](https://github.com/containerd/containerd/commit/024b1cce6b27f10e00bb9bde33a5fe9563545f8d) update to go1.20.11, test go1.21.4
* [release/1.6] Add cri-api v1alpha2 usage warning to all api calls ([#9484](https://github.com/containerd/containerd/pull/9484))
  * [`64e56bfde`](https://github.com/containerd/containerd/commit/64e56bfde95828660971673d20952f275cc2c0ba) Add cri-api v1alpha2 usage warning to all api calls
* [release/1.6] tasks: emit warning for v1 runtime and runc v1 runtime ([#9468](https://github.com/containerd/containerd/pull/9468))
  * [`efefd3bf3`](https://github.com/containerd/containerd/commit/efefd3bf334b5df0e97bff0be61ba906a9b3b528) tasks: emit warning for runc v1 runtime
  * [`7825689b4`](https://github.com/containerd/containerd/commit/7825689b4c4d68cc1cc3c6dd072c2c2ec7b2d88e) tasks: emit warning for v1 runtime
* [release/1.6] snapshots: emit deprecation warning for aufs ([#9448](https://github.com/containerd/containerd/pull/9448))
  * [`7cfe7052f`](https://github.com/containerd/containerd/commit/7cfe7052f4a2ad97e4e8032469aef588d2f0858c) snapshots: emit deprecation warning for aufs
* [release/1.6] cherry-pick/backport: Update golangci lint ([#9455](https://github.com/containerd/containerd/pull/9455))
  * [`a1ae572a2`](https://github.com/containerd/containerd/commit/a1ae572a2778bf599e93929f5145f707b667f508) Fix linter error with updated linter
  * [`b638791d6`](https://github.com/containerd/containerd/commit/b638791d66b2e34f044f04736632995446b79314) ci: bump up golangci-lint to v1.55.0
  * [`2370a2842`](https://github.com/containerd/containerd/commit/2370a2842318833b16a8274835374d0811c2ed28) Fix linter issues for golangci-lint 1.54.2
  * [`8a65e2e31`](https://github.com/containerd/containerd/commit/8a65e2e31b6710f94be64c7fada727bd2569d16f) Bump up golangci-lint to v1.54.2
  * [`969f8feb2`](https://github.com/containerd/containerd/commit/969f8feb2e0932a9f9c69f1696e552fcdcd2b31b) Bump up golangci-lint to v1.52.2
* [release/1.6] push: inherit distribution sources from parent ([#9453](https://github.com/containerd/containerd/pull/9453))
  * [`66959fdf5`](https://github.com/containerd/containerd/commit/66959fdf50d16520a84fb14c9467c0d87b7f0274) push: inherit distribution sources from parent
  * [`b4dcffcfb`](https://github.com/containerd/containerd/commit/b4dcffcfbff2694796a04243728700b37dc78d8e) content: add InfoProvider interface
  * [`bef4145c1`](https://github.com/containerd/containerd/commit/bef4145c141ad2c37e7797b4dc53b8e429b368ae) Change PushContent to require only Provider
* [release/1.6] Bump google.golang.org/grpc to v1.58.3 ([#9408](https://github.com/containerd/containerd/pull/9408))
  * [`a5fc21060`](https://github.com/containerd/containerd/commit/a5fc21060b5254be9ca28e63c1c5a7364b551ca5) vendor: google.golang.org/grpc v1.58.3
  * [`4fa05b3d8`](https://github.com/containerd/containerd/commit/4fa05b3d83488e4bc81241db1a65ca00fedec45d) Upgrade github.com/klauspost/compress from v1.11.13 to v1.15.9
* [release/1.6] Windows default path overwrite fix ([#9441](https://github.com/containerd/containerd/pull/9441))
  * [`ede0ad5e1`](https://github.com/containerd/containerd/commit/ede0ad5e12826d574623a79b71bb1fbc49e75172) Fix windows default path overwrite issue
</p>
</details>

### Dependency Changes

* **cloud.google.com/go/compute/metadata**  v0.2.3 **_new_**
* **github.com/cespare/xxhash/v2**          v2.1.2 -> v2.2.0
* **github.com/golang/protobuf**            v1.5.2 -> v1.5.3
* **github.com/klauspost/compress**         v1.11.13 -> v1.15.9
* **go.opencensus.io**                      v0.23.0 -> v0.24.0
* **golang.org/x/oauth2**                   2bc19b11175f -> v0.10.0
* **golang.org/x/sync**                     v0.1.0 -> v0.3.0
* **google.golang.org/grpc**                v1.50.1 -> v1.58.3
* **google.golang.org/protobuf**            v1.28.1 -> v1.31.0

Previous release can be found at [v1.6.25](https://github.com/containerd/containerd/releases/tag/v1.6.25)
## kubernetes/kubeadm

**Section:**

- [ ] Developer News
- [ ] Release Schedule
- [ ] Featured PRs
- [ ] Other Merges
- [ ] Version Promotions/ Graduates
- [ ] Deprecated
- [ ] Version Updates
- [x] Related Projects
- [ ] Not Sure / Other

To include updates from projects other than `Kubernetes` and `Kubernetes/sigs`, please refer to the [list of projects]() we accept submissions from.

**Comment by mfahlandt** [comment]
/assign @jberkus @fykaa @sreeram-venkitesh 

AS discussed in Slack for now the Release notes as Issue

**Comment by sreeram-venkitesh** [comment]
Thanks to @mfahlandt for the script! The [issue](https://lwkd.info/2023/20231213) for week ending with December 10 was published thanks to the data scraped by the script!
