### ISSUE TITLE
News Item: enforce https on this repo to enable http to https redirect

### ISSUE THREAD

**Issue by boredabdel** [kubernetes-sigs/lwkd#292]
**Your Item for LWKD**
While checking the github pages serving lkwd.info I realised http to https redirect is not enabled. You can still visit http://lkwd.info and it will work without https

You can enforce https in the settings part of this repo and github will automatically redirect from http to https https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

**Comment by jberkus** [comment]
We can obviously do this.  Should we, though?

@coderanger @sreeram-venkitesh @fykaa @mfahlandt ?

LWKD has zero interactive components, so we're not protecting anyone's security by disabling HTTP.  Thoughts?

**Comment by boredabdel** [comment]
These are all valid point. I have few reasons for to why https should be the default

- Any modern browser will display a scary non-secure message in the address bar if people try to go to the http version of the website
- Google ranks non-https website very low. In fact if you search for "Kubernetes Development" lwkd doesn't show on the first page of search results.
- All in all http to https redirect is a common practice these days.

**Comment by sreeram-venkitesh** [comment]
+1 from me as well for enforcing https.

**Comment by fykaa** [comment]
Yes, considering the potential security warnings in modern browsers and the impact on Google rankings, it seems like a reasonable step to take! As for the concerns about the lack of interactive components in LWKD, I believe that adopting HTTPS is not just about protecting interactive components but also about overall web security and user trust, so +1

**Comment by jberkus** [comment]
Done, thanks.
