### ISSUE TITLE
Suggested improvement: link to this repo

### ISSUE THREAD

**Issue by porridge** [kubernetes-sigs/lwkd#382]
**Your Item for LWKD**

It would be nice to link to this repo in the footnote such that readers can raise editorial issues.

**Links for Your Item**

Link 1 : https://github.com/kubernetes-sigs/lwkd

**Section:**

- [ ] Developer News
- [ ] Release Schedule
- [ ] Featured PRs
- [ ] Other Merges
- [ ] Version Promotions/ Graduates
- [ ] Deprecated
- [ ] Version Updates
- [ ] Related Projects
- [x] Not Sure / Other: Footnote

To include updates from projects other than `Kubernetes` and `Kubernetes/sigs`, please refer to the [list of projects]() we accept submissions from.

**Comment by jberkus** [comment]
Added a couple issues ago; seems to be working.  Check the footer of each edition.

Thanks for the report!
